pipeline {
    agent any
    stages
    {
        stage('SCM')
        {
            steps
            {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Chatbrume/ManagerAccountMicroServices.git']]])
            }
        }
        stage('Compile')
        {
            steps
            {
                bat 'mvn clean compile'
            }
        }
        stage('Test')
        {
            steps
            {
                script
                {
                    try
                    {
                        bat 'mvn test'
                    }
                    finally
                    {
                        step([$class: 'JUnitResultArchiver', testResults: '**/target/site/jacoco/*.xml'])
                    }
                }
            }
        }

        stage('Docs') {
            steps{
                bat 'mvn javadoc:javadoc'
            }
        }
    }
}