pipeline {
    agent any
    tools {
        jdk 'JDK_1.8_221'
        maven 'MavenInstallation'
    }
    environment {
        String branchName = "main"
        String repoUrl = "https://github.com/Chatbrume/ManagerAccountMicroServices.git"
    }
    stages {
        stage('Checkout') {
            steps {
                script {
                    echo 'Cloning the "'+branchName+'" branch from "'+repoUrl+'".'
                    echo 'Start cloning the github repository...'
                    git branch: branchName, url: repoUrl
                    echo 'repository clone on branch master done.'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    echo 'Execute all test...'
                    withMaven {
                        bat "cd ManagerAccountService"
                        bat "mvn clean test"
                    }
                    echo 'End of the execution'
                }
            }
        }
        stage('generate javadoc') {
            steps {
                script {
                    echo 'Generation of the javadoc...'
                    withMaven {
                        bat "mvn javadoc:javadoc"
                    }
                    echo 'The javadoc have been generated !'
                }
            }

        }
        stage('confirmation email') {
            steps {
                emailext attachLog: true, body: 'ManagerAccount jenkins pipeline build finished with success', subject: '[Jenkins] ManagerAccount', to: 'nioche.amelie@gmail.com'
                echo 'An email have been send ! Consult your email adress !'
            }
        }
    }
}